/**
 * DSL Runtime 开发服务器
 * 
 * 🎯 基于 Vite 的开发服务器，用于运行 DSL 项目
 */

import { createServer, type ViteDevServer } from 'vite';
import path from 'path';
import fs from 'fs';
import { createRequire, Module } from 'module';
import { fileURLToPath } from 'url';
import type { DSLProjectConfig } from './loader.js';

// 创建 require 函数用于解析模块路径
const require = createRequire(import.meta.url);

// 🎯 跨平台兼容：使用 fileURLToPath 正确处理 Windows 和 Mac/Linux 路径
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// dsl-runtime 包的根目录
const runtimePackageDir = path.resolve(__dirname, '..');

/**
 * 解析包路径（从 pnpm 的 .pnpm 目录或 workspace 中）
 */
function resolvePackage(packageName: string): string {
  // monorepo 根目录
  const monoRepoRoot = path.join(runtimePackageDir, '../..');
  
  // 尝试从 workspace 包解析（如 @ai-builder/runtime-renderer）
  if (packageName.startsWith('@ai-builder/')) {
    const workspacePath = path.join(monoRepoRoot, 'packages', packageName.replace('@ai-builder/', ''));
    if (fs.existsSync(workspacePath)) {
      return workspacePath;
    }
  }
  
  // 使用 require.resolve 获取模块的实际路径
  try {
    const resolved = require.resolve(packageName + '/package.json', { paths: [runtimePackageDir] });
    return path.dirname(resolved);
  } catch {
    // 忽略错误，继续尝试其他方式
  }
  
  // 返回原始包名，让 Vite 自己解析
  return packageName;
}

/**
 * 生成虚拟入口文件内容
 */
function generateEntryContent(config: DSLProjectConfig): string {
  const dslPath = path.join(config.root, config.srcDir).replace(/\\/g, '/');
  const initSqlPath = config.database?.initSql 
    ? path.join(config.root, config.database.initSql).replace(/\\/g, '/')
    : null;

  return `
/**
 * 🎯 Auto-generated by DSL Runtime
 * 这是由 dsl-runtime 自动生成的入口文件
 */

import 'reflect-metadata';
import React from 'react';
import ReactDOM from 'react-dom/client';
import { ConfigProvider, Layout, Menu, Spin, Alert, Avatar, Dropdown, Space } from 'antd';
import { 
  OrderedListOutlined, 
  DatabaseOutlined, 
  SettingOutlined,
  HomeOutlined,
  UserOutlined,
  LogoutOutlined,
} from '@ant-design/icons';
import zhCN from 'antd/locale/zh_CN';

import { 
  createDSLRouter,
  registerComponents,
  getLayeredStats,
  initDatabase,
  getMenuRoutes,
  useNavigate,
  getMergedAppConfig,
  vnodeToReactElement,
} from '@qwe8652591/dsl-core';

import { getAntdComponentMapping } from '@dsl-runtime/antd-components/adapter';

// 🎯 动态导入 DSL 定义（必须先导入，让装饰器注册 metadata）
import '${dslPath}';

// 导入路由配置
import { routes } from '${dslPath}/routes';

${initSqlPath ? `import initSqlContent from '${initSqlPath}?raw';` : ''}

// 注册 Antd 组件
registerComponents(getAntdComponentMapping());

// 创建路由
const { router, Provider: AppRouter } = createDSLRouter(routes, {
  fallback: (
    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
      <Spin size="large" tip="加载中..." />
    </div>
  ),
  notFound: (
    <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
      <Alert type="warning" message="404 - 页面不存在" />
    </div>
  ),
});

// 图标映射
const iconMap: Record<string, React.ReactNode> = {
  OrderedListOutlined: <OrderedListOutlined />,
  DatabaseOutlined: <DatabaseOutlined />,
  SettingOutlined: <SettingOutlined />,
  HomeOutlined: <HomeOutlined />,
};

// 从 CDN 加载 sql.js
async function loadSqlJsFromCDN(): Promise<any> {
  if ((window as any).initSqlJs) {
    return (window as any).initSqlJs;
  }
  
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = 'https://sql.js.org/dist/sql-wasm.js';
    script.onload = () => {
      if ((window as any).initSqlJs) {
        resolve((window as any).initSqlJs);
      } else {
        reject(new Error('sql.js failed to load'));
      }
    };
    script.onerror = reject;
    document.head.appendChild(script);
  });
}

// 侧边菜单组件
function SideMenu({ currentPath }: { currentPath: string }) {
  const navigate = useNavigate();
  const menuRoutes = getMenuRoutes(routes);
  
  const menuItems = menuRoutes.map(route => ({
    key: route.path,
    icon: route.menu?.icon ? iconMap[route.menu.icon] : null,
    label: route.menu?.label || route.title,
  }));
  
  const handleMenuClick = ({ key }: { key: string }) => {
    navigate(key);
  };
  
  return (
    <Menu
      mode="inline"
      selectedKeys={[currentPath]}
      style={{ height: 'calc(100% - 64px)', borderRight: 0 }}
      items={menuItems}
      onClick={handleMenuClick}
    />
  );
}

// 获取当前路由的标题
function getPageTitle(path: string, appName: string): string {
  const route = routes.find(r => {
    if (r.path === path) return true;
    // 支持动态路由匹配 /orders/:id
    const pattern = r.path.replace(/:[^/]+/g, '[^/]+');
    return new RegExp(\`^\${pattern}$\`).test(path);
  });
  return route?.title || appName;
}

// 渲染 DSL 插槽组件
function renderSlot(slotComponent: any, props: any = {}): React.ReactNode {
  if (!slotComponent) return null;
  
  // 如果是 DSL 组件定义，执行 setup 并转换为 React
  if (slotComponent.setup && typeof slotComponent.setup === 'function') {
    try {
      const result = slotComponent.setup(props);
      
      // setup 返回渲染函数，需要调用它获取 VNode
      if (typeof result === 'function') {
        const vnode = result();
        if (vnode && typeof vnode === 'object' && 'type' in vnode) {
          return vnodeToReactElement(vnode);
        }
        return vnode;
      }
      
      // 兼容：直接返回 VNode 的情况
      if (result && typeof result === 'object' && 'type' in result) {
        return vnodeToReactElement(result);
      }
      
      return result;
    } catch (e) {
      console.error('[Slot] Failed to render:', slotComponent.meta?.name || slotComponent.name, e);
      return null;
    }
  }
  
  return null;
}

// 应用布局组件
function AppLayout({ children }: { children: React.ReactNode }) {
  // 🎯 从 Metadata 获取应用配置
  const appConfig = getMergedAppConfig();
  const slots = (appConfig as any).slots || {};
  
  const [currentPath, setCurrentPath] = React.useState(() => {
    return typeof window !== 'undefined' ? window.location.hash.replace('#', '') || '/orders' : '/orders';
  });
  
  // 监听路由变化
  React.useEffect(() => {
    const handleHashChange = () => {
      setCurrentPath(window.location.hash.replace('#', '') || '/orders');
    };
    window.addEventListener('hashchange', handleHashChange);
    return () => window.removeEventListener('hashchange', handleHashChange);
  }, []);
  
  const pageTitle = getPageTitle(currentPath, appConfig.name);
  const menuWidth = appConfig.menu?.width || 220;
  const headerHeight = appConfig.header?.height || 56;
  
  // 默认用户下拉菜单
  const defaultUserMenu = (
    <Dropdown 
      menu={{ 
        items: [
          { key: 'profile', icon: <UserOutlined />, label: '个人信息' },
          { key: 'settings', icon: <SettingOutlined />, label: '设置' },
          { type: 'divider' as const },
          { key: 'logout', icon: <LogoutOutlined />, label: '退出登录', danger: true },
        ]
      }} 
      placement="bottomRight"
    >
      <Space style={{ cursor: 'pointer' }}>
        <Avatar icon={<UserOutlined />} style={{ backgroundColor: appConfig.theme?.primaryColor || '#1890ff' }} />
        <span>管理员</span>
      </Space>
    </Dropdown>
  );
  
  // 渲染头部右侧
  const headerRightContent = slots.headerRight 
    ? renderSlot(slots.headerRight, { pageTitle, currentPath })
    : (appConfig.header?.showUser !== false ? defaultUserMenu : null);
  
  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Layout.Sider 
        width={menuWidth} 
        theme="light" 
        style={{ 
          boxShadow: '2px 0 8px rgba(0,0,0,0.06)',
          position: 'fixed',
          left: 0,
          top: 0,
          bottom: 0,
          zIndex: 100,
          display: 'flex',
          flexDirection: 'column',
        }}
      >
        {/* 侧边栏头部 */}
        {slots.sidebarHeader ? (
          renderSlot(slots.sidebarHeader, { currentPath })
        ) : (
          <div style={{ 
            height: 64, 
            display: 'flex', 
            alignItems: 'center', 
            justifyContent: 'center',
            borderBottom: '1px solid #f0f0f0',
            fontWeight: 600,
            fontSize: 16,
          }}>
            {appConfig.logo || '🚀'} {appConfig.name}
          </div>
        )}
        
        {/* 菜单 */}
        <div style={{ flex: 1, overflow: 'auto' }}>
          <SideMenu currentPath={currentPath} />
        </div>
        
        {/* 侧边栏底部 */}
        {slots.sidebarFooter && renderSlot(slots.sidebarFooter, { currentPath })}
      </Layout.Sider>
      
      <Layout style={{ marginLeft: menuWidth }}>
        {/* 头部栏 */}
        <Layout.Header style={{ 
          background: '#fff', 
          padding: '0 24px', 
          display: 'flex', 
          alignItems: 'center', 
          justifyContent: 'space-between',
          borderBottom: '1px solid #f0f0f0',
          position: 'sticky',
          top: 0,
          zIndex: 99,
          height: headerHeight,
          lineHeight: \`\${headerHeight}px\`,
        }}>
          {/* 头部左侧 */}
          {slots.headerLeft ? (
            renderSlot(slots.headerLeft, { pageTitle, currentPath })
          ) : (
            <h2 style={{ margin: 0, fontSize: 18, fontWeight: 500 }}>
              {pageTitle}
            </h2>
          )}
          
          {/* 头部右侧 */}
          {headerRightContent}
        </Layout.Header>
        
        {/* 内容区 */}
        <Layout.Content style={{ background: '#fff' }}>
          {children}
        </Layout.Content>
      </Layout>
    </Layout>
  );
}

// 应用组件
function App() {
  const [ready, setReady] = React.useState(false);
  const [error, setError] = React.useState<Error | null>(null);

  React.useEffect(() => {
    async function init() {
      try {
        // 动态加载 sql.js（从 CDN）
        const initSqlJs = await loadSqlJsFromCDN();
        
        // 初始化数据库（使用配置）
        await initDatabase({
          type: 'sqlite',
          sqlJsModule: initSqlJs,
          persistKey: '${config.database?.persistKey || 'dsl-app-db'}',
          ${initSqlPath ? `mockDataSQL: initSqlContent,
          loadMockData: true,
          checkTable: '${config.database?.checkTable || ''}',` : ''}
          debug: ${config.database?.debug ?? false},
        });
        
        // 打印 DSL 统计
        const stats = getLayeredStats();
        console.log('📊 DSL Metadata Statistics:', stats);
        
        setReady(true);
      } catch (err) {
        console.error('Failed to initialize:', err);
        setError(err as Error);
      }
    }
    
    init();
  }, []);

  if (error) {
    return (
      <ConfigProvider locale={zhCN}>
        <div style={{ padding: 40 }}>
          <Alert 
            type="error" 
            message="初始化失败" 
            description={<pre style={{ margin: 0 }}>{error.message}</pre>}
            showIcon
          />
        </div>
      </ConfigProvider>
    );
  }

  if (!ready) {
    return (
      <ConfigProvider locale={zhCN}>
        <div style={{ 
          display: 'flex', 
          justifyContent: 'center', 
          alignItems: 'center', 
          height: '100vh',
          flexDirection: 'column',
          gap: 16,
        }}>
          <Spin size="large" />
          <span>正在初始化应用...</span>
        </div>
      </ConfigProvider>
    );
  }

  return (
    <ConfigProvider locale={zhCN}>
      <AppLayout>
        <AppRouter />
      </AppLayout>
    </ConfigProvider>
  );
}

// 挂载应用
const root = ReactDOM.createRoot(document.getElementById('root')!);
root.render(<App />);
`;
}

/**
 * 生成 HTML 模板
 */
function generateHtmlTemplate(): string {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>DSL Runtime</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; }
  </style>
  <!-- sql.js from CDN -->
  <script src="https://sql.js.org/dist/sql-wasm.js"></script>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/@dsl-entry"></script>
</body>
</html>`;
}

/**
 * 创建开发服务器
 */
export async function createDevServer(config: DSLProjectConfig): Promise<ViteDevServer> {
  const htmlTemplate = generateHtmlTemplate();
  
  // 获取 dsl-runtime 包的路径（使用跨平台兼容的方式）
  const runtimePath = __dirname;
  
  // DSL 项目路径
  const dslPath = path.join(config.root, config.srcDir).replace(/\\/g, '/');
  const initSqlPath = config.database?.initSql 
    ? path.join(config.root, config.database.initSql).replace(/\\/g, '/')
    : null;
  
  console.log(`📝 Using runtime entry from dsl-runtime package`);
  console.log(`   Runtime path: ${runtimePath}`);

  const server = await createServer({
    // 使用 DSL 项目作为根目录
    root: config.root,
    
    server: {
      port: config.server?.port || 3000,
      host: config.server?.host || 'localhost',
      // 🎯 允许访问 dsl-runtime 包的文件
      fs: {
        allow: [config.root, runtimePackageDir, path.join(runtimePackageDir, '..')]
      }
    },
    
    plugins: [
      // HTML 入口插件
      {
        name: 'dsl-runtime-html',
        
        configureServer(server) {
          // 拦截根路径，返回 HTML
          server.middlewares.use((req, res, next) => {
            if (req.url === '/' || req.url === '/index.html') {
              res.setHeader('Content-Type', 'text/html');
              res.end(htmlTemplate);
              return;
            }
            next();
          });
        },
      },
      
      // 🎯 虚拟入口模块插件
      {
        name: 'dsl-runtime-entry',
        enforce: 'pre' as const,
        
        resolveId(id) {
          if (id === '/@dsl-entry') {
            return '\0dsl-entry';
          }
          // 解析运行时入口别名
          if (id === '@dsl-runtime/entry') {
            // runtimePath 指向 dist 目录，runtime-entry.tsx 在 src 目录
            return path.join(runtimePath, '../src/runtime-entry.tsx');
          }
        },
        
        load(id) {
          if (id === '\0dsl-entry') {
            // 生成入口代码 - 使用别名而不是绝对路径
            return `
import { render } from '@dsl-runtime/entry';

// 导入 DSL 定义
import '${dslPath}';

// 导入路由配置
import { routes } from '${dslPath}/routes';

${initSqlPath ? `import initSqlContent from '${initSqlPath}?raw';` : 'const initSqlContent = undefined;'}

// 设置数据库配置
window.__DATABASE_CONFIG__ = ${JSON.stringify({
              persistKey: config.database?.persistKey || config.name || 'dsl-app',
              checkTable: config.database?.checkTable,
            })};

// 渲染应用
render(routes, initSqlContent);
`;
          }
        },
      },
      
      // sql.js 拦截插件（从 CDN 加载，不打包）
      {
        name: 'dsl-runtime-sql-js',
        enforce: 'pre' as const,
        
        resolveId(id) {
          if (id === 'sql.js') {
            return '\0sql-js-stub';
          }
        },
        
        load(id) {
          if (id === '\0sql-js-stub') {
            return `
              export default function() {
                throw new Error('sql.js should be loaded from CDN');
              }
            `;
          }
        },
      },
    ],
    
    resolve: {
      alias: {
        '@': path.join(config.root, 'src'),
        // sql.js 从 CDN 加载，返回空模块
        'sql.js': path.join(runtimePath, '../empty-module.js'),
        
        // 🎯 运行时依赖从 dsl-runtime 包解析
        'react': resolvePackage('react'),
        'react-dom': resolvePackage('react-dom'),
        'react-router-dom': resolvePackage('react-router-dom'),
        'antd': resolvePackage('antd'),
        '@ant-design/icons': resolvePackage('@ant-design/icons'),
        'reflect-metadata': resolvePackage('reflect-metadata'),
        
        // 🎯 AI Builder 包从 workspace 解析
        '@ai-builder/runtime-renderer': resolvePackage('@ai-builder/runtime-renderer'),
        '@qwe8652591/dsl-core': resolvePackage('@qwe8652591/dsl-core'),
        '@qwe8652591/std-ui': resolvePackage('@qwe8652591/std-ui'),
      },
      // 确保运行时依赖不会被重复加载
      dedupe: ['react', 'react-dom', 'react-router-dom', 'antd', '@ant-design/icons'],
    },
    
    optimizeDeps: {
      // 预构建这些依赖（包括 dayjs 插件，解决 ESM/CJS 兼容问题）
      include: [
        'react', 
        'react-dom', 
        'react-router-dom', 
        'antd', 
        '@ant-design/icons',
        'dayjs',
        'dayjs/plugin/weekday',
        'dayjs/plugin/localeData',
        'dayjs/plugin/weekOfYear',
        'dayjs/plugin/weekYear',
        'dayjs/plugin/advancedFormat',
        'dayjs/plugin/customParseFormat',
      ],
      // 排除 sql.js（从 CDN 加载）
      exclude: ['sql.js'],
      // 只扫描 DSL 目录
      entries: [path.join(config.root, config.srcDir, '**/*.{ts,tsx}')],
    },
    
    esbuild: {
      jsx: 'automatic',
      jsxImportSource: 'react',
    },
  });

  return server;
}
